{% set version = "1.9-16" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ptw
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ptw_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ptw/ptw_{{ version }}.tar.gz
  sha256: 7e87c34b9eeaeabe3bfb937162e6cda4dd48d6bd6a97b9db8bb8303d131caa66

build:
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcppde
  run:
    - r-base
    - r-rcppde

test:
  commands:
    - $R -e "library('ptw')"           # [not win]
    - "\"%R%\" -e \"library('ptw')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ptw
  license: GPL-2.0-or-later
  summary: 'Parametric Time Warping aligns patterns, i.e. it aims to put corresponding features at the same locations. The algorithm searches for an optimal polynomial describing the warping. It is possible to align one sample to a reference, several samples to the same reference, or several samples to several references.
    One can choose between calculating individual warpings, or one global warping for a set of samples and one reference. Two optimization criteria are implemented: RMS (Root Mean Square error) and WCC (Weighted Cross Correlation). Both warping of peak profiles and of peak lists are supported.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ptw
# Type: Package
# Title: Parametric Time Warping
# Version: 1.9-13
# Authors@R: c(person("Jan", "Gerretzen", role = "ctb"), person("Paul", "Eilers", role = "aut"), person("Hans", "Wouters", role = "ctb"), person("Tom", "Bloemberg", role = "aut", email = "t.bloemberg@science.ru.nl"), person("Ron", "Wehrens", role = c("aut", "cre"), email = "ron.wehrens@gmail.com"))
# Description: Parametric Time Warping aligns patterns, i.e. it aims to put corresponding features at the same locations. The algorithm searches for an optimal polynomial describing the warping. It is possible to align one sample to a reference, several samples to the same reference, or several samples to several references. One can choose between calculating individual warpings, or one global warping for a set of samples and one reference. Two optimization criteria are implemented: RMS (Root Mean Square error) and WCC (Weighted Cross Correlation). Both warping of peak profiles and of peak lists are supported.
# License: GPL (>= 2)
# Imports: nloptr, graphics, grDevices, stats
# NeedsCompilation: yes
# Packaged: 2018-05-25 08:13:45 UTC; ron
# Author: Jan Gerretzen [ctb], Paul Eilers [aut], Hans Wouters [ctb], Tom Bloemberg [aut], Ron Wehrens [aut, cre]
# Maintainer: Ron Wehrens <ron.wehrens@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-25 22:17:57 UTC
