# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LpWlbtXUEhJx1hUs6z2tt1CVludQ34m1xPMUILmawy5+6J/sfqqti+glW0Ws+paB0rfXR2xzFcKUrdHxaRLWZt4O0RF///Yn9JOlf6Ta7wsgYqty6+oSqDloWCyHtaWmbcFZJtyD1GWOm+zKOrIFH7TTfUDX175imkfYR2XW0U1PpZhhUlzKLadJwU2/qaKDX0XYQ9y8HR5LrvoSUbDK+hHmYesSNsA92ywhgfxDmjKB6K+W18l1EAhImM0N75CE4UuQtl+rw45PcJiFNaXrbzxjpk4dnKuxG1dWtP4qj/vPHr32fXC2xcH96ts2XED4LPxIho6f5GPqU8RdUIAk3I9GZ3uHe/VRCge3A2+X5Ji33NJbqlvwz++jX/eF8EFjKPm7vF4vk8TD2Euvt/W9mJbhMbmD96bhd7eLW07W4qhImNM0UOvR1KKK3b/TJwP63Y07Y3bPXcA92vqDH7xHBLkGbd76lQI/XaY4yk5sKOGy8nDk5fkcLqG++0oyQS7WBqvduNZP+7YLRCPq3jR/F8JWS6I/Lh/eMgiQbI9uUh0KVWy/YvMUm2z45TiUQFnyA3hu8ReDHqEde+lOI2lOHgoyG3C1iqYYnyjtF+yoV3Y47yP2LIuqNovbQiv4tXpuoj1AFlW8gmQOWmjgcnGY57Ju7QcrGezCr88TtiVTMWI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
