travis:
  secure:
    BINSTAR_TOKEN: uCIltWruGVGqTI9NOqJkXRMJb/XEpNDMpreCqWNvkC61iL+oOmzk36iVtwdKV6VVxE3B4zZ6vY/e+ik+BGdUpFIkBnbECaL2pFNqLgtf+HmsH48zqCTunQHnfN4zuegOUo86Ky39M2e8+TYv6hE3NU6HVrFHjgltr72H9gOmvKQoZJ0/Bt9mIHxxbtDrQEbnL6tSzysVa9YxDn+2Y9e86AEBZNVKFDG2Gt0zO/svkxyeT/MxV4bxJdSBUEoFN3Wp5YZQvHztAfPjd79H5rXpoWlfLsTDkiKzghH7xmQk9Lfpwwujh7+8GuVaa42HPtQb7XoxgzTe52Edp970uNDsKuVnDQ4X7dnw1ejFasnVvZV9tr7ERy3X2hskE+7MzciwF3RtPe0lcW4N3FrQBy/fKp8o8qJrvQYPSI2JnxjIvF1wBiZCjNN3fOl29WVK2pqQt/P39hsHhk0J1mNXlvRYl0d1Q2c4eLPlIbT78ZLgtf7WEeQz4ZMLVydtp+jKUiNi5zl/4IFsf78axC6stkTo3TpHFgpGyFtRzeT5UE/8iWc5c3yxhcWjtHpuaYrzmnQzZ741WLLB1HwkghMtNvqscwVWxpf6AcrWJmaZVeuYGNb/pwFUXL7hj7pkYufAl6oADOZJeTF/IxC6dfT6WdKIpLpFOapg3KP0+Jf7u9L+oEU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
