travis:
  secure:
    BINSTAR_TOKEN: CLWI43xAf23LOvW01VcqrMvuAZTdHdq+ShsMyg6TvDZHTrQkSOHP7eg0K7C6DteiprhdVJd0ARpiK8QYWOEgyHSYOn5z/U3sBcp/kiVtrKmM3DzW+UWNZ/URybxpuS7RT6XBoswAZTGIR7TdF+ZkA9kSy+JhH90h4BqRE8jD1ziqctsnk/3fXWVqsXflLj4Mzi7TIf6bb01NfUSHVj/7DnOj8Oun/NjUKF4ICPKZPrHBKHZ47Cs7AnXGZ9P5ArRl931j7lP2xcYruYQQh38rTDp+3ZT6umoagUcbAHktaxXKfTOKlZv5y3kRGKBU15j6y9KXmGt2Jzcf/PCf1r25d3Fh9EiHPvwtzuPzSoLGGRGem13JfD7AiXH6e31Gel5Tm28TW2yLhPQoCYqIM1ArnuGhW23QKu3boUGwdahc3f0PYsH7k+vGVrLhf8kVuQhvLVbDylKMZpj7qhwfdzO1NHRODS4mAnAqd+6TuTpiHXWzqVHEVPy+FLR5ipo2oqjw6TVQQbZ26k0AFbsQc6R3jPV5CgcwvvrjHP5jnz0fqhKQ7vg0YU6PgbPo/ErqF71TMeCl6yjM8HmQJUrSbTNfpe31X52yVJmBmlJPKbT13c0gE4Y3VqUb6rmZk56IDgrUo7KYtQT5+w1KQ4qHV8Ca8Nlvb0dODJa6nB4FegbsZoA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
