travis:
  secure:
    BINSTAR_TOKEN: LpWlbtXUEhJx1hUs6z2tt1CVludQ34m1xPMUILmawy5+6J/sfqqti+glW0Ws+paB0rfXR2xzFcKUrdHxaRLWZt4O0RF///Yn9JOlf6Ta7wsgYqty6+oSqDloWCyHtaWmbcFZJtyD1GWOm+zKOrIFH7TTfUDX175imkfYR2XW0U1PpZhhUlzKLadJwU2/qaKDX0XYQ9y8HR5LrvoSUbDK+hHmYesSNsA92ywhgfxDmjKB6K+W18l1EAhImM0N75CE4UuQtl+rw45PcJiFNaXrbzxjpk4dnKuxG1dWtP4qj/vPHr32fXC2xcH96ts2XED4LPxIho6f5GPqU8RdUIAk3I9GZ3uHe/VRCge3A2+X5Ji33NJbqlvwz++jX/eF8EFjKPm7vF4vk8TD2Euvt/W9mJbhMbmD96bhd7eLW07W4qhImNM0UOvR1KKK3b/TJwP63Y07Y3bPXcA92vqDH7xHBLkGbd76lQI/XaY4yk5sKOGy8nDk5fkcLqG++0oyQS7WBqvduNZP+7YLRCPq3jR/F8JWS6I/Lh/eMgiQbI9uUh0KVWy/YvMUm2z45TiUQFnyA3hu8ReDHqEde+lOI2lOHgoyG3C1iqYYnyjtF+yoV3Y47yP2LIuqNovbQiv4tXpuoj1AFlW8gmQOWmjgcnGY57Ju7QcrGezCr88TtiVTMWI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
