travis:
  secure:
    BINSTAR_TOKEN: ubM7Z01A111RjC3ngjTtd0NGNU8neGQ1xrBORHYC7mzuHPBUrnMUtyEVFASs5iQb8Bns/FjCInV837KrjvTsT1prVWvoJSMyU35TgDpL5xw4G9pHIOWYddsAzZypPkygjkPbpwD85q0sc5mSXNUvuEl88wMQL7x4bj8S7PnHjF2+YVX+Y7pVPmcdlc6S3j0cJFsqprZxmU96eKDkypxedh7OuOKE7BkcjBHG40pHIrsG7WYkL+Q6+0GFJL0oxcquzJqx1pTYeWZsZ+MRFSCagNTtOJ7uzQiVMv/7GrxdzowXLUqc7UP5q3qsJ2I216b5MAQLjgfTBydjOrxD6qAzrqTiRygQ62pQs49JaO/QWd79dh5o0wb91h5q3/qtJO17zCKyevMDOGJxAjh3AGIKgeVJBGI77g69TuLNjNjtnTOsD3HfIcVzcQxb/a1XtZu9u02nrM82X4xPnMEgACHiziUjxsE9aMiu2xo1iSwgybE6bAUtK7KVLnw4fXmF3oD9WurNIN5/3yumOq26DsgrTuP/KbNzZUnUKjeNPMGHDrzbjt93jqrtaSHwr++cJEMldz6eUR8oGpuwAF2wQ2rquBpmsKP3LgaEPxEA96PPfpOcoOYvAYO5XIS7qTd8ivObwsRFECliq/6/DK6zw84x7s01z5NprshPS41eJQfaRgs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
