travis:
  secure:
    BINSTAR_TOKEN: ODF6IGf0MbuAEJkuOPwIniOw8JlYvcLmzWqaaybE8jv0KB/mh5wjxHi16rj+YYjcOjpot4J/9L3cYRg5hwVn4efH0gnrPNQnbab6DIySY8nv4TlMpSgEyHr9NoP2Bs/mvq26y/ICWyprU2EeKBz3D3SWjeHK55EMEiK3N9/Uy3uBdKb+hoJbAr7doMr1sCeqPZZbU87VGQfUh4yIVPmyKIr3IpWQv2uYUHpaTpxTQ2Eb8uuEojXYh3BuGdgpRAmysIoie4r7okeG+3AAG1Hg2wO47DbvvdgWy3VpPWdFdVO+JHhkTkRWyY+G07eJayadqotYImTw/KocOkL/8P1pBeEo4d+im4PylNmjsGBjvs3IyjasAVE/vZnsRMQEYmSCe0NlYS/QSMsLWzJSLGs56UAsIWFYdLuNkVgJqcX5cEtOJTv+HeDXeX2XyAljyNde7I8ZfPefl4zCvk0+m4X5G8mKy3TPEenMuhjbrZlVdP8UYcwAhmPsryq/jYzEVNSpl7EqXioBV05kj5tLmWXA6Uf8QuycSx8soHIsl0kUHc/GrOEfIMixna78wDWLn9P31rGzoF8tnkKbVCguZFXkZVlymVllkP3kerOYDDQxhsyFD0LhdSdNNmqxGYArJpmqh2iBRcDtJFET3sJIuz2iHcxrb63ipL8loOaWc2Gdd68=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
